prog_cfg:
  # bag_file: !!path /home/loc/loc_ws/src/IVFC-Localization/data/11.13.bag
  bag_file: /home/loc/loc_ws/data/sjtu.bag
  bag_rate: 1
  queue_size: 100

  gps_status_valid: 2

  # pointcloud2 | livox
  lidar_type: pointcloud2
  lidar_topic: /driver/hesai/pandar
  gps_topic: /Inertial/gps/fix
  imu_topic: /Inertial/imu/data

app_cfg:
  voxel_cfg:
    max_num_voxels: 150000
    max_num_points: 10
    resolution: 0.5
    min_distance: 0.1

  reg_cfg_track:
    max_iterations: 100
    robust_kernel: 0.0
    rotation_epsilon: 1e-3
    translation_epsilon: 1e-3

  reg_cfg_loop:
    max_iterations: 100
    robust_kernel: 0.0
    rotation_epsilon: 1e-2
    translation_epsilon: 1e-2

  enable_deskew: true
  enable_loopclosure: true
  update_local_map: true
  enable_incremental_mapping: true
  # lidar -> gps
  extinct: [0, 1.15, -1.96]
  # extinct: []
  # imu -> body(gps)
  imu_extinct: [0, 0, 1.5524763267948967]

  static_frames: 1
  range_min: 4
  range_max: 250
  tracking_voxel: 1.0
  mapping_voxel: 2.0

  loop_frame_skip: 600
  loop_trials_num: 10
  loop_distance_threshold: 20
  loop_interval_ms: 1000
  loop_overlap_threshold: 0.9
  loop_fitness_threshold: 0.1
  loop_local_frames: 1000