#STATIC_MODE: 0, DYNAMIC_MODE: 1
overlap_mode: 1
voxel_leaf: 0.1
total_time_s: 3.0
wait_time_s: 1.0
frame_process_num: 2400
is_save_cloud: false

# 6 elements: Translation + Euler(z,y,x)
# if transformation in other node(like iekf3d), use[0...]
car2gimbal_transformation: [0.0, 0.0, 0.0, 0, 0, 0]

# 3 elements: Translation(x,y,z) in meter
device_bias_trans: [0.0354, 0.0003, -0.0034]