#STATIC_MODE: 0, DYNAMIC_MODE: 1
overlap_mode: 1
voxel_leaf: 0.1
total_time_s: 3.0
wait_time_s: 1.0
frame_process_num: 2400
is_save_cloud: false

# 6 elements: Translation + Euler(z,y,x)
# if transformation in other node(like iekf3d), use[0...]
car2gimbal_transformation: [0.0, 0.0, 0.0, 0, 0, 0]

# map_path: /home/wuby/localization/Servo-Lidar-Loclization/data/para1.ply
# map_voxel_leaf: 10
# normal_estimate_radius: 0.2
# local_range: 200
# update_range: 50
# points_interval: 1 #in icp, now advised to be 1

# ### 6 elements: Translation + Euler(x,y,z)
# ### 7 elements: Translation + Quaternion(x,y,z,w)
# initialpose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# icp:
#   voxel_leaf:     0.5
#   iterations:     20
#   distance_thres: 5.0
#   planefit_thres: 0.2
#   robust_kernel:  0.1
#   translation_epsilon: 0.01
#   rotation_epsilon: 0.001
#   min_points_per_frame: 100
# #frame_skip_num: 4